// Centralized mock data for the entire application

// Product data
export const products = [
  {
    id: 1,
    name: 'Modern Sofa',
    price: 1299,
    discount: 1499,
    category: 'Living Room',
    style: 'Modern',
    material: 'Fabric',
    color: 'Gray',
    rating: 4.5,
    reviews: 128,
    stock: 15,
    description:
      'A comfortable and stylish sofa that will elevate your living room. Made with high-quality materials for durability and comfort.',
    features: [
      'Solid wood frame for durability',
      'High-density foam cushions for comfort',
      'Stain-resistant fabric upholstery',
      'Removable and washable covers',
      'Easy assembly with included tools',
    ],
    specifications: {
      dimensions: '84" W x 38" D x 34" H',
      weight: '120 lbs',
      material: 'Fabric, Wood, Foam',
      assembly: 'Required, tools included',
      warranty: '3 years limited warranty',
    },
    colors: ['Gray', 'Blue', 'Beige', 'Green'],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-0.webp',
    images: [
      '/products/converted-image-0.webp',
      '/products/converted-image-1.webp',
      '/products/converted-image-2.webp',
      '/products/converted-image-3.webp',
    ],
  },
  {
    id: 2,
    name: 'Ergonomic Office Chair',
    price: 349,
    discount: null,
    category: 'Office',
    style: 'Contemporary',
    material: 'Mesh',
    color: 'Black',
    rating: 4.8,
    reviews: 95,
    stock: 23,
    description:
      'An ergonomic office chair designed for comfort during long work hours. Features adjustable height and lumbar support.',
    features: [
      'Adjustable height and armrests',
      'Breathable mesh back',
      'Lumbar support',
      '360-degree swivel',
      'Durable casters for smooth movement',
    ],
    specifications: {
      dimensions: '26" W x 26" D x 38-42" H',
      weight: '35 lbs',
      material: 'Mesh, Metal, Plastic',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['Black', 'Gray', 'Blue'],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-1.webp',
    images: [
      '/products/converted-image-2.webp',
      '/products/converted-image-3.webp',
      '/products/converted-image-4.webp',
      '/products/converted-image-5.webp',
    ],
  },
  {
    id: 3,
    name: 'Minimalist Coffee Table',
    price: 499,
    discount: null,
    category: 'Living Room',
    style: 'Minimalist',
    material: 'Wood',
    color: 'Natural',
    rating: 4.2,
    reviews: 67,
    stock: 18,
    description:
      'A sleek, minimalist coffee table that adds a touch of elegance to your living room. Features a spacious surface and storage shelf.',
    features: [
      'Solid wood construction',
      'Lower shelf for storage',
      'Smooth, rounded edges',
      'Water-resistant finish',
      'Non-slip feet',
    ],
    specifications: {
      dimensions: '48" W x 24" D x 18" H',
      weight: '45 lbs',
      material: 'Solid Oak Wood',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['Natural', 'Walnut', 'Black'],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-2.webp',
    images: [
      '/products/converted-image-2.webp',
      '/products/converted-image-3.webp',
      '/products/converted-image-4.webp',
      '/products/converted-image-5.webp',
    ],
  },
  {
    id: 4,
    name: 'Scandinavian Bed Frame',
    price: 899,
    discount: 999,
    category: 'Bedroom',
    style: 'Scandinavian',
    material: 'Wood',
    color: 'White',
    rating: 4.7,
    reviews: 112,
    stock: 8,
    description:
      'A beautiful Scandinavian-style bed frame that brings simplicity and elegance to your bedroom. Features a sturdy design and clean lines.',
    features: [
      'Solid pine wood construction',
      'Slatted base for ventilation',
      'No box spring needed',
      'Clean, minimalist design',
      'Easy assembly',
    ],
    specifications: {
      dimensions: '65" W x 86" D x 40" H (Queen)',
      weight: '95 lbs',
      material: 'Solid Pine Wood',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['White', 'Natural', 'Gray'],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-3.webp',
    images: [
      '/products/converted-image-4.webp',
      '/products/converted-image-5.webp',
      '/products/converted-image-6.webp',
      '/products/converted-image-7.webp',
    ],
  },
  {
    id: 5,
    name: 'Classic Dining Set',
    price: 1899,
    discount: null,
    category: 'Dining Room',
    style: 'Classic',
    material: 'Wood',
    color: 'Brown',
    rating: 4.6,
    reviews: 89,
    stock: 5,
    description:
      'A timeless dining set that includes a table and six chairs. Perfect for family gatherings and dinner parties.',
    features: [
      'Solid hardwood construction',
      'Table extends to seat 8',
      'Comfortable upholstered chairs',
      'Scratch-resistant finish',
      'Protective floor pads',
    ],
    specifications: {
      dimensions: 'Table: 72" W x 42" D x 30" H',
      weight: '220 lbs (set)',
      material: 'Hardwood, Fabric',
      assembly: 'Required, professional assembly recommended',
      warranty: '3 years limited warranty',
    },
    colors: ['Brown', 'Cherry', 'Espresso'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-4.webp',
    images: [
      '/products/converted-image-5.webp',
      '/products/converted-image-6.webp',
      '/products/converted-image-7.webp',
      '/products/converted-image-8.webp',
    ],
  },
  {
    id: 6,
    name: 'Leather Recliner',
    price: 799,
    discount: 899,
    category: 'Living Room',
    style: 'Traditional',
    material: 'Leather',
    color: 'Brown',
    rating: 4.4,
    reviews: 76,
    stock: 12,
    description:
      'A luxurious leather recliner that offers exceptional comfort and style. Features multiple reclining positions and plush cushioning.',
    features: [
      'Genuine leather upholstery',
      'Multiple reclining positions',
      'Padded armrests and headrest',
      'Sturdy frame construction',
      'Easy-to-use reclining mechanism',
    ],
    specifications: {
      dimensions: '38" W x 40" D x 40" H',
      weight: '110 lbs',
      material: 'Genuine Leather, Wood',
      assembly: 'Minimal assembly required',
      warranty: '2 years limited warranty',
    },
    colors: ['Brown', 'Black', 'Tan'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-5.webp',
    images: [
      '/products/converted-image-6.webp',
      '/products/converted-image-7.webp',
      '/products/converted-image-8.webp',
      '/products/converted-image-9.webp',
    ],
  },
  {
    id: 7,
    name: 'Queen Size Mattress',
    price: 649,
    discount: null,
    category: 'Bedroom',
    style: 'Modern',
    material: 'Memory Foam',
    color: 'White',
    rating: 4.9,
    reviews: 203,
    stock: 25,
    description:
      'A premium memory foam mattress that contours to your body for optimal comfort and support. Helps reduce pressure points and improve sleep quality.',
    features: [
      'Multiple layers of premium foam',
      'Breathable cover for temperature regulation',
      'Motion isolation technology',
      'Hypoallergenic materials',
      'CertiPUR-US certified foams',
    ],
    specifications: {
      dimensions: '60" W x 80" D x 12" H (Queen)',
      weight: '70 lbs',
      material: 'Memory Foam, Polyfoam',
      assembly: 'No assembly required',
      warranty: '10 years limited warranty',
    },
    colors: ['White'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-6.webp',
    images: [
      '/products/converted-image-7.webp',
      '/products/converted-image-8.webp',
      '/products/converted-image-9.webp',
      '/products/converted-image-10.webp',
    ],
  },
  {
    id: 8,
    name: 'Wooden Bookshelf',
    price: 399,
    discount: null,
    category: 'Office',
    style: 'Rustic',
    material: 'Wood',
    color: 'Natural',
    rating: 4.3,
    reviews: 58,
    stock: 14,
    description:
      'A rustic wooden bookshelf with five shelves, perfect for displaying books, photos, and decorative items. Adds warmth and character to any room.',
    features: [
      'Solid wood construction',
      'Five spacious shelves',
      'Rustic finish with natural wood grain',
      'Anti-tip safety feature',
      'Adjustable shelf heights',
    ],
    specifications: {
      dimensions: '36" W x 12" D x 72" H',
      weight: '65 lbs',
      material: 'Solid Pine Wood',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['Natural', 'Walnut', 'Espresso'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-7.webp',
    images: [
      '/products/converted-image-8.webp',
      '/products/converted-image-9.webp',
      '/products/converted-image-10.webp',
      '/products/converted-image-11.webp',
    ],
  },
  {
    id: 9,
    name: 'Modular Sectional Sofa',
    price: 2199,
    discount: 2499,
    category: 'Living Room',
    style: 'Contemporary',
    material: 'Fabric',
    color: 'Gray',
    rating: 4.7,
    reviews: 92,
    stock: 7,
    description:
      'A versatile modular sectional sofa that can be arranged in multiple configurations to suit your space and needs. Features plush cushions and durable fabric.',
    features: [
      'Modular design for flexible arrangements',
      'Stain-resistant performance fabric',
      'High-density foam cushions',
      'Solid hardwood frame',
      'Removable and washable covers',
    ],
    specifications: {
      dimensions: 'Varies based on configuration',
      weight: '250 lbs (total)',
      material: 'Performance Fabric, Hardwood, Foam',
      assembly: 'Required, tools included',
      warranty: '3 years limited warranty',
    },
    colors: ['Gray', 'Navy', 'Beige', 'Charcoal'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-8.webp',
    images: [
      '/products/converted-image-9.webp',
      '/products/converted-image-10.webp',
      '/products/converted-image-11.webp',
      '/products/converted-image-12.webp',
    ],
  },
  {
    id: 10,
    name: 'Marble Dining Table',
    price: 1499,
    discount: null,
    category: 'Dining Room',
    style: 'Modern',
    material: 'Marble',
    color: 'White',
    rating: 4.5,
    reviews: 45,
    stock: 3,
    description:
      'An elegant dining table featuring a genuine marble top and sleek metal base. Makes a stunning centerpiece for any dining room.',
    features: [
      'Genuine marble tabletop',
      'Sturdy metal base',
      'Seats up to 6 people',
      'Protective coating on marble surface',
      'Adjustable feet for stability',
    ],
    specifications: {
      dimensions: '72" W x 36" D x 30" H',
      weight: '180 lbs',
      material: 'Marble, Metal',
      assembly: 'Required, professional assembly recommended',
      warranty: '2 years limited warranty',
    },
    colors: ['White Marble', 'Black Marble'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-9.webp',
    images: [
      '/products/converted-image-10.webp',
      '/products/converted-image-11.webp',
      '/products/converted-image-12.webp',
      '/products/converted-image-13.webp',
    ],
  },
  {
    id: 11,
    name: 'Smart Bedside Table',
    price: 299,
    discount: null,
    category: 'Bedroom',
    style: 'Modern',
    material: 'Wood',
    color: 'White',
    rating: 4.6,
    reviews: 38,
    stock: 20,
    description:
      'A modern bedside table with built-in wireless charging, USB ports, and ambient lighting. Combines functionality with contemporary style.',
    features: [
      'Built-in wireless charging pad',
      'USB charging ports',
      'Soft-close drawer',
      'Integrated ambient lighting',
      'Cable management system',
    ],
    specifications: {
      dimensions: '20" W x 16" D x 24" H',
      weight: '30 lbs',
      material: 'Engineered Wood, Metal',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['White', 'Black', 'Oak'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-10.webp',
    images: [
      '/products/converted-image-11.webp',
      '/products/converted-image-12.webp',
      '/products/converted-image-13.webp',
      '/products/converted-image-14.webp',
    ],
  },
  {
    id: 12,
    name: 'Adjustable Standing Desk',
    price: 749,
    discount: 849,
    category: 'Office',
    style: 'Contemporary',
    material: 'Wood',
    color: 'Black',
    rating: 4.8,
    reviews: 72,
    stock: 9,
    description:
      'An electric adjustable standing desk that allows you to switch between sitting and standing throughout your workday. Features a spacious desktop and memory settings.',
    features: [
      'Electric height adjustment',
      'Memory settings for preferred heights',
      'Spacious desktop surface',
      'Cable management tray',
      'Anti-collision technology',
    ],
    specifications: {
      dimensions: '60" W x 30" D x 25-50" H',
      weight: '120 lbs',
      material: 'Engineered Wood, Steel',
      assembly: 'Required, tools included',
      warranty: '5 years limited warranty',
    },
    colors: ['Black', 'White', 'Walnut'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-11.webp',
    images: [
      '/products/converted-image-12.webp',
      '/products/converted-image-13.webp',
      '/products/converted-image-14.webp',
      '/products/converted-image-15.webp',
    ],
  },
  {
    id: 13,
    name: 'Kitchen Island Cart',
    price: 399,
    discount: null,
    category: 'Kitchen',
    style: 'Farmhouse',
    material: 'Wood',
    color: 'White',
    rating: 4.4,
    reviews: 56,
    stock: 11,
    description:
      'A versatile kitchen island cart with a butcher block top, storage drawers, and shelves. Perfect for adding extra workspace and storage to your kitchen.',
    features: [
      'Solid wood butcher block top',
      'Two storage drawers',
      'Two open shelves',
      'Towel bar',
      'Locking casters for mobility',
    ],
    specifications: {
      dimensions: '36" W x 20" D x 36" H',
      weight: '75 lbs',
      material: 'Solid Wood, Metal',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['White', 'Natural', 'Gray'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-12.webp',
    images: [
      '/products/converted-image-13.webp',
      '/products/converted-image-14.webp',
      '/products/converted-image-15.webp',
      '/products/converted-image-16.webp',
    ],
  },
  {
    id: 14,
    name: 'Outdoor Dining Set',
    price: 899,
    discount: 1099,
    category: 'Outdoor',
    style: 'Modern',
    material: 'Metal',
    color: 'Black',
    rating: 4.3,
    reviews: 42,
    stock: 6,
    description:
      'A stylish outdoor dining set including a table and four chairs. Weather-resistant materials make it perfect for patios, decks, and gardens.',
    features: [
      'Weather-resistant materials',
      'Powder-coated aluminum frame',
      'Tempered glass tabletop',
      'Quick-dry mesh seating',
      'Stackable chairs for easy storage',
    ],
    specifications: {
      dimensions: 'Table: 48" W x 48" D x 29" H',
      weight: '85 lbs (set)',
      material: 'Aluminum, Glass, Mesh',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['Black', 'White', 'Bronze'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-13.webp',
    images: [
      '/products/converted-image-14.webp',
      '/products/converted-image-15.webp',
      '/products/converted-image-16.webp',
      '/products/converted-image-17.webp',
    ],
  },
  {
    id: 15,
    name: 'Floor Lamp',
    price: 179,
    discount: null,
    category: 'Lighting',
    style: 'Contemporary',
    material: 'Metal',
    color: 'Black',
    rating: 4.5,
    reviews: 63,
    stock: 22,
    description:
      'A sleek, contemporary floor lamp with adjustable height and direction. Perfect for reading or adding ambient lighting to any room.',
    features: [
      'Adjustable height and angle',
      'Energy-efficient LED bulb included',
      'Foot pedal switch',
      'Weighted base for stability',
      'Compatible with smart home systems',
    ],
    specifications: {
      dimensions: '12" W x 12" D x 60-72" H',
      weight: '15 lbs',
      material: 'Metal, Fabric',
      assembly: 'Required, no tools needed',
      warranty: '1 year limited warranty',
    },
    colors: ['Black', 'Brass', 'Nickel'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-14.webp',
    images: [
      '/products/converted-image-15.webp',
      '/products/converted-image-16.webp',
      '/products/converted-image-17.webp',
      '/products/converted-image-18.webp',
    ],
  },
  {
    id: 16,
    name: 'Accent Chair',
    price: 349,
    discount: 399,
    category: 'Living Room',
    style: 'Mid-Century',
    material: 'Fabric',
    color: 'Blue',
    rating: 4.6,
    reviews: 87,
    stock: 13,
    description:
      'A stylish mid-century inspired accent chair that adds a pop of color and character to any room. Features comfortable cushioning and tapered wooden legs.',
    features: [
      'High-quality upholstery fabric',
      'Foam cushioning for comfort',
      'Solid wood frame and legs',
      'Non-marking foot pads',
      'Weight capacity: 300 lbs',
    ],
    specifications: {
      dimensions: '28" W x 30" D x 32" H',
      weight: '35 lbs',
      material: 'Fabric, Wood, Foam',
      assembly: 'Minimal assembly required',
      warranty: '1 year limited warranty',
    },
    colors: ['Blue', 'Gray', 'Green', 'Mustard'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-15.webp',
    images: [
      '/products/converted-image-16.webp',
      '/products/converted-image-17.webp',
      '/products/converted-image-18.webp',
      '/products/converted-image-19.webp',
    ],
  },
  {
    id: 17,
    name: 'Modern Dining Table',
    price: 1299,
    discount: 1499,
    category: 'Dining Room',
    style: 'Modern',
    material: 'Wood',
    color: 'Black',
    rating: 4.7,
    reviews: 92,
    stock: 7,
    description:
      'A modern dining table with a sleek design and a solid wood frame. Features a tempered glass top and a metal base.',
    features: [
      'Tempered glass top',
      'Metal base',
      'Easy assembly with included tools',
      'Weight capacity: 1000 lbs',
    ],
    specifications: {
      dimensions: '120" W x 60" D x 30" H',
      weight: '150 lbs',
      material: 'Wood, Glass, Metal',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['Black', 'White', 'Oak'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-16.webp',
    images: [
      '/products/converted-image-17.webp',
      '/products/converted-image-18.webp',
      '/products/converted-image-19.webp',
      '/products/converted-image-20.webp',
    ],
  },
]

// Categories data
export const categories = [
  {
    id: 'living-room',
    name: 'Living Room',
    description: 'Furniture for your living space',
    image: '/categories/LivingRoom.webp',
  },
  {
    id: 'bedroom',
    name: 'Bedroom',
    description: 'Create your perfect sleep sanctuary',
    image: '/products/converted-image-26.webp',
  },
  {
    id: 'dining-room',
    name: 'Dining Room',
    description: 'Elegant dining furniture',
    image: '/products/converted-image-12.webp',
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    description: 'Functional kitchen furniture',
    image: '/categories/Kitchen.webp',
  },
  {
    id: 'office',
    name: 'Office',
    description: 'Professional workspace furniture',
    image: '/categories/Office.webp',
  },
  {
    id: 'outdoor',
    name: 'Outdoor',
    description: 'Durable outdoor furniture',
    image: '/categories/Outdoor.webp',
  },
  {
    id: 'lighting',
    name: 'Lighting',
    description: 'Illuminate your space',
    image: '/products/converted-image-19.webp',
  },
]

// User data
export const users = [
  {
    id: 'USR-1234',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    phone: '+1 (555) 123-4567',
    avatar: '/placeholder.svg?height=100&width=100',
    memberSince: 'January 2023',
    points: 250,
    role: 'Customer',
    status: 'Active',
    orders: 12,
    joined: '2023-01-15',
  },
  {
    id: 'USR-1235',
    name: 'Michael Chen',
    email: 'michael.chen@example.com',
    role: 'Customer',
    status: 'Active',
    orders: 8,
    joined: '2023-02-22',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'USR-1236',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    role: 'Customer',
    status: 'Active',
    orders: 5,
    joined: '2023-03-10',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'USR-1237',
    name: 'Robert Wilson',
    email: 'robert.wilson@example.com',
    role: 'Customer',
    status: 'Inactive',
    orders: 0,
    joined: '2023-04-05',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'USR-1238',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@example.com',
    role: 'Customer',
    status: 'Active',
    orders: 15,
    joined: '2023-01-05',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'USR-1239',
    name: 'David Martinez',
    email: 'david.martinez@example.com',
    role: 'Admin',
    status: 'Active',
    orders: 0,
    joined: '2022-11-15',
    avatar: '/placeholder.svg?height=40&width=40',
  },
]

// Order data
export const orders = [
  {
    id: 'ORD-12345',
    date: '2023-11-15',
    status: 'Delivered',
    total: 1799.97,
    items: [
      { name: 'Modern Sofa', price: 1299, quantity: 1 },
      { name: 'Coffee Table', price: 499, quantity: 1 },
    ],
  },
  {
    id: 'ORD-12346',
    date: '2023-10-22',
    status: 'Delivered',
    total: 349.99,
    items: [
      { name: 'Floor Lamp', price: 179.99, quantity: 1 },
      { name: 'Decorative Pillows', price: 89, quantity: 2 },
    ],
  },
  {
    id: 'ORD-12347',
    date: '2023-12-05',
    status: 'Processing',
    total: 899,
    items: [{ name: 'Dining Table', price: 899, quantity: 1 }],
  },
  {
    id: 1,
    name: 'Modern Sofa',
    price: 1299,
    discount: 1499,
    category: 'Living Room',
    style: 'Modern',
    material: 'Fabric',
    color: 'Gray',
    rating: 4.5,
    reviews: 128,
    stock: 15,
    description:
      'A comfortable and stylish sofa that will elevate your living room. Made with high-quality materials for durability and comfort.',
    features: [
      'Solid wood frame for durability',
      'High-density foam cushions for comfort',
      'Stain-resistant fabric upholstery',
      'Removable and washable covers',
      'Easy assembly with included tools',
    ],
    specifications: {
      dimensions: '84" W x 38" D x 34" H',
      weight: '120 lbs',
      material: 'Fabric, Wood, Foam',
      assembly: 'Required, tools included',
      warranty: '3 years limited warranty',
    },
    colors: ['Gray', 'Blue', 'Beige', 'Green'],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-0.webp',
    images: [
      '/products/converted-image-0.webp',
      '/products/converted-image-1.webp',
      '/products/converted-image-2.webp',
      '/products/converted-image-3.webp',
    ],
  },
  {
    id: 2,
    name: 'Ergonomic Office Chair',
    price: 349,
    discount: null,
    category: 'Office',
    style: 'Contemporary',
    material: 'Mesh',
    color: 'Black',
    rating: 4.8,
    reviews: 95,
    stock: 23,
    description:
      'An ergonomic office chair designed for comfort during long work hours. Features adjustable height and lumbar support.',
    features: [
      'Adjustable height and armrests',
      'Breathable mesh back',
      'Lumbar support',
      '360-degree swivel',
      'Durable casters for smooth movement',
    ],
    specifications: {
      dimensions: '26" W x 26" D x 38-42" H',
      weight: '35 lbs',
      material: 'Mesh, Metal, Plastic',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['Black', 'Gray', 'Blue'],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-1.webp',
    images: [
      '/products/converted-image-2.webp',
      '/products/converted-image-3.webp',
      '/products/converted-image-4.webp',
      '/products/converted-image-5.webp',
    ],
  },
  {
    id: 3,
    name: 'Minimalist Coffee Table',
    price: 499,
    discount: null,
    category: 'Living Room',
    style: 'Minimalist',
    material: 'Wood',
    color: 'Natural',
    rating: 4.2,
    reviews: 67,
    stock: 18,
    description:
      'A sleek, minimalist coffee table that adds a touch of elegance to your living room. Features a spacious surface and storage shelf.',
    features: [
      'Solid wood construction',
      'Lower shelf for storage',
      'Smooth, rounded edges',
      'Water-resistant finish',
      'Non-slip feet',
    ],
    specifications: {
      dimensions: '48" W x 24" D x 18" H',
      weight: '45 lbs',
      material: 'Solid Oak Wood',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['Natural', 'Walnut', 'Black'],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-2.webp',
    images: [
      '/products/converted-image-2.webp',
      '/products/converted-image-3.webp',
      '/products/converted-image-4.webp',
      '/products/converted-image-5.webp',
    ],
  },
  {
    id: 4,
    name: 'Scandinavian Bed Frame',
    price: 899,
    discount: 999,
    category: 'Bedroom',
    style: 'Scandinavian',
    material: 'Wood',
    color: 'White',
    rating: 4.7,
    reviews: 112,
    stock: 8,
    description:
      'A beautiful Scandinavian-style bed frame that brings simplicity and elegance to your bedroom. Features a sturdy design and clean lines.',
    features: [
      'Solid pine wood construction',
      'Slatted base for ventilation',
      'No box spring needed',
      'Clean, minimalist design',
      'Easy assembly',
    ],
    specifications: {
      dimensions: '65" W x 86" D x 40" H (Queen)',
      weight: '95 lbs',
      material: 'Solid Pine Wood',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['White', 'Natural', 'Gray'],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-3.webp',
    images: [
      '/products/converted-image-4.webp',
      '/products/converted-image-5.webp',
      '/products/converted-image-6.webp',
      '/products/converted-image-7.webp',
    ],
  },
  {
    id: 5,
    name: 'Classic Dining Set',
    price: 1899,
    discount: null,
    category: 'Dining Room',
    style: 'Classic',
    material: 'Wood',
    color: 'Brown',
    rating: 4.6,
    reviews: 89,
    stock: 5,
    description:
      'A timeless dining set that includes a table and six chairs. Perfect for family gatherings and dinner parties.',
    features: [
      'Solid hardwood construction',
      'Table extends to seat 8',
      'Comfortable upholstered chairs',
      'Scratch-resistant finish',
      'Protective floor pads',
    ],
    specifications: {
      dimensions: 'Table: 72" W x 42" D x 30" H',
      weight: '220 lbs (set)',
      material: 'Hardwood, Fabric',
      assembly: 'Required, professional assembly recommended',
      warranty: '3 years limited warranty',
    },
    colors: ['Brown', 'Cherry', 'Espresso'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-4.webp',
    images: [
      '/products/converted-image-5.webp',
      '/products/converted-image-6.webp',
      '/products/converted-image-7.webp',
      '/products/converted-image-8.webp',
    ],
  },
  {
    id: 6,
    name: 'Leather Recliner',
    price: 799,
    discount: 899,
    category: 'Living Room',
    style: 'Traditional',
    material: 'Leather',
    color: 'Brown',
    rating: 4.4,
    reviews: 76,
    stock: 12,
    description:
      'A luxurious leather recliner that offers exceptional comfort and style. Features multiple reclining positions and plush cushioning.',
    features: [
      'Genuine leather upholstery',
      'Multiple reclining positions',
      'Padded armrests and headrest',
      'Sturdy frame construction',
      'Easy-to-use reclining mechanism',
    ],
    specifications: {
      dimensions: '38" W x 40" D x 40" H',
      weight: '110 lbs',
      material: 'Genuine Leather, Wood',
      assembly: 'Minimal assembly required',
      warranty: '2 years limited warranty',
    },
    colors: ['Brown', 'Black', 'Tan'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-5.webp',
    images: [
      '/products/converted-image-6.webp',
      '/products/converted-image-7.webp',
      '/products/converted-image-8.webp',
      '/products/converted-image-9.webp',
    ],
  },
  {
    id: 7,
    name: 'Queen Size Mattress',
    price: 649,
    discount: null,
    category: 'Bedroom',
    style: 'Modern',
    material: 'Memory Foam',
    color: 'White',
    rating: 4.9,
    reviews: 203,
    stock: 25,
    description:
      'A premium memory foam mattress that contours to your body for optimal comfort and support. Helps reduce pressure points and improve sleep quality.',
    features: [
      'Multiple layers of premium foam',
      'Breathable cover for temperature regulation',
      'Motion isolation technology',
      'Hypoallergenic materials',
      'CertiPUR-US certified foams',
    ],
    specifications: {
      dimensions: '60" W x 80" D x 12" H (Queen)',
      weight: '70 lbs',
      material: 'Memory Foam, Polyfoam',
      assembly: 'No assembly required',
      warranty: '10 years limited warranty',
    },
    colors: ['White'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-6.webp',
    images: [
      '/products/converted-image-7.webp',
      '/products/converted-image-8.webp',
      '/products/converted-image-9.webp',
      '/products/converted-image-10.webp',
    ],
  },
  {
    id: 8,
    name: 'Wooden Bookshelf',
    price: 399,
    discount: null,
    category: 'Office',
    style: 'Rustic',
    material: 'Wood',
    color: 'Natural',
    rating: 4.3,
    reviews: 58,
    stock: 14,
    description:
      'A rustic wooden bookshelf with five shelves, perfect for displaying books, photos, and decorative items. Adds warmth and character to any room.',
    features: [
      'Solid wood construction',
      'Five spacious shelves',
      'Rustic finish with natural wood grain',
      'Anti-tip safety feature',
      'Adjustable shelf heights',
    ],
    specifications: {
      dimensions: '36" W x 12" D x 72" H',
      weight: '65 lbs',
      material: 'Solid Pine Wood',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['Natural', 'Walnut', 'Espresso'],
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    image: '/products/converted-image-7.webp',
    images: [
      '/products/converted-image-8.webp',
      '/products/converted-image-9.webp',
      '/products/converted-image-10.webp',
      '/products/converted-image-11.webp',
    ],
  },
  {
    id: 9,
    name: 'Modular Sectional Sofa',
    price: 2199,
    discount: 2499,
    category: 'Living Room',
    style: 'Contemporary',
    material: 'Fabric',
    color: 'Gray',
    rating: 4.7,
    reviews: 92,
    stock: 7,
    description:
      'A versatile modular sectional sofa that can be arranged in multiple configurations to suit your space and needs. Features plush cushions and durable fabric.',
    features: [
      'Modular design for flexible arrangements',
      'Stain-resistant performance fabric',
      'High-density foam cushions',
      'Solid hardwood frame',
      'Removable and washable covers',
    ],
    specifications: {
      dimensions: 'Varies based on configuration',
      weight: '250 lbs (total)',
      material: 'Performance Fabric, Hardwood, Foam',
      assembly: 'Required, tools included',
      warranty: '3 years limited warranty',
    },
    colors: ['Gray', 'Navy', 'Beige', 'Charcoal'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-8.webp',
    images: [
      '/products/converted-image-9.webp',
      '/products/converted-image-10.webp',
      '/products/converted-image-11.webp',
      '/products/converted-image-12.webp',
    ],
  },
  {
    id: 10,
    name: 'Marble Dining Table',
    price: 1499,
    discount: null,
    category: 'Dining Room',
    style: 'Modern',
    material: 'Marble',
    color: 'White',
    rating: 4.5,
    reviews: 45,
    stock: 3,
    description:
      'An elegant dining table featuring a genuine marble top and sleek metal base. Makes a stunning centerpiece for any dining room.',
    features: [
      'Genuine marble tabletop',
      'Sturdy metal base',
      'Seats up to 6 people',
      'Protective coating on marble surface',
      'Adjustable feet for stability',
    ],
    specifications: {
      dimensions: '72" W x 36" D x 30" H',
      weight: '180 lbs',
      material: 'Marble, Metal',
      assembly: 'Required, professional assembly recommended',
      warranty: '2 years limited warranty',
    },
    colors: ['White Marble', 'Black Marble'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-9.webp',
    images: [
      '/products/converted-image-10.webp',
      '/products/converted-image-11.webp',
      '/products/converted-image-12.webp',
      '/products/converted-image-13.webp',
    ],
  },
  {
    id: 11,
    name: 'Smart Bedside Table',
    price: 299,
    discount: null,
    category: 'Bedroom',
    style: 'Modern',
    material: 'Wood',
    color: 'White',
    rating: 4.6,
    reviews: 38,
    stock: 20,
    description:
      'A modern bedside table with built-in wireless charging, USB ports, and ambient lighting. Combines functionality with contemporary style.',
    features: [
      'Built-in wireless charging pad',
      'USB charging ports',
      'Soft-close drawer',
      'Integrated ambient lighting',
      'Cable management system',
    ],
    specifications: {
      dimensions: '20" W x 16" D x 24" H',
      weight: '30 lbs',
      material: 'Engineered Wood, Metal',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['White', 'Black', 'Oak'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-10.webp',
    images: [
      '/products/converted-image-11.webp',
      '/products/converted-image-12.webp',
      '/products/converted-image-13.webp',
      '/products/converted-image-14.webp',
    ],
  },
  {
    id: 12,
    name: 'Adjustable Standing Desk',
    price: 749,
    discount: 849,
    category: 'Office',
    style: 'Contemporary',
    material: 'Wood',
    color: 'Black',
    rating: 4.8,
    reviews: 72,
    stock: 9,
    description:
      'An electric adjustable standing desk that allows you to switch between sitting and standing throughout your workday. Features a spacious desktop and memory settings.',
    features: [
      'Electric height adjustment',
      'Memory settings for preferred heights',
      'Spacious desktop surface',
      'Cable management tray',
      'Anti-collision technology',
    ],
    specifications: {
      dimensions: '60" W x 30" D x 25-50" H',
      weight: '120 lbs',
      material: 'Engineered Wood, Steel',
      assembly: 'Required, tools included',
      warranty: '5 years limited warranty',
    },
    colors: ['Black', 'White', 'Walnut'],
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    image: '/products/converted-image-11.webp',
    images: [
      '/products/converted-image-12.webp',
      '/products/converted-image-13.webp',
      '/products/converted-image-14.webp',
      '/products/converted-image-15.webp',
    ],
  },
  {
    id: 13,
    name: 'Kitchen Island Cart',
    price: 399,
    discount: null,
    category: 'Kitchen',
    style: 'Farmhouse',
    material: 'Wood',
    color: 'White',
    rating: 4.4,
    reviews: 56,
    stock: 11,
    description:
      'A versatile kitchen island cart with a butcher block top, storage drawers, and shelves. Perfect for adding extra workspace and storage to your kitchen.',
    features: [
      'Solid wood butcher block top',
      'Two storage drawers',
      'Two open shelves',
      'Towel bar',
      'Locking casters for mobility',
    ],
    specifications: {
      dimensions: '36" W x 20" D x 36" H',
      weight: '75 lbs',
      material: 'Solid Wood, Metal',
      assembly: 'Required, tools included',
      warranty: '1 year limited warranty',
    },
    colors: ['White', 'Natural', 'Gray'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-12.webp',
    images: [
      '/products/converted-image-13.webp',
      '/products/converted-image-14.webp',
      '/products/converted-image-15.webp',
      '/products/converted-image-16.webp',
    ],
  },
  {
    id: 14,
    name: 'Outdoor Dining Set',
    price: 899,
    discount: 1099,
    category: 'Outdoor',
    style: 'Modern',
    material: 'Metal',
    color: 'Black',
    rating: 4.3,
    reviews: 42,
    stock: 6,
    description:
      'A stylish outdoor dining set including a table and four chairs. Weather-resistant materials make it perfect for patios, decks, and gardens.',
    features: [
      'Weather-resistant materials',
      'Powder-coated aluminum frame',
      'Tempered glass tabletop',
      'Quick-dry mesh seating',
      'Stackable chairs for easy storage',
    ],
    specifications: {
      dimensions: 'Table: 48" W x 48" D x 29" H',
      weight: '85 lbs (set)',
      material: 'Aluminum, Glass, Mesh',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['Black', 'White', 'Bronze'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-13.webp',
    images: [
      '/products/converted-image-14.webp',
      '/products/converted-image-15.webp',
      '/products/converted-image-16.webp',
      '/products/converted-image-17.webp',
    ],
  },
  {
    id: 15,
    name: 'Floor Lamp',
    price: 179,
    discount: null,
    category: 'Lighting',
    style: 'Contemporary',
    material: 'Metal',
    color: 'Black',
    rating: 4.5,
    reviews: 63,
    stock: 22,
    description:
      'A sleek, contemporary floor lamp with adjustable height and direction. Perfect for reading or adding ambient lighting to any room.',
    features: [
      'Adjustable height and angle',
      'Energy-efficient LED bulb included',
      'Foot pedal switch',
      'Weighted base for stability',
      'Compatible with smart home systems',
    ],
    specifications: {
      dimensions: '12" W x 12" D x 60-72" H',
      weight: '15 lbs',
      material: 'Metal, Fabric',
      assembly: 'Required, no tools needed',
      warranty: '1 year limited warranty',
    },
    colors: ['Black', 'Brass', 'Nickel'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-14.webp',
    images: [
      '/products/converted-image-15.webp',
      '/products/converted-image-16.webp',
      '/products/converted-image-17.webp',
      '/products/converted-image-18.webp',
    ],
  },
  {
    id: 16,
    name: 'Accent Chair',
    price: 349,
    discount: 399,
    category: 'Living Room',
    style: 'Mid-Century',
    material: 'Fabric',
    color: 'Blue',
    rating: 4.6,
    reviews: 87,
    stock: 13,
    description:
      'A stylish mid-century inspired accent chair that adds a pop of color and character to any room. Features comfortable cushioning and tapered wooden legs.',
    features: [
      'High-quality upholstery fabric',
      'Foam cushioning for comfort',
      'Solid wood frame and legs',
      'Non-marking foot pads',
      'Weight capacity: 300 lbs',
    ],
    specifications: {
      dimensions: '28" W x 30" D x 32" H',
      weight: '35 lbs',
      material: 'Fabric, Wood, Foam',
      assembly: 'Minimal assembly required',
      warranty: '1 year limited warranty',
    },
    colors: ['Blue', 'Gray', 'Green', 'Mustard'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-15.webp',
    images: [
      '/products/converted-image-16.webp',
      '/products/converted-image-17.webp',
      '/products/converted-image-18.webp',
      '/products/converted-image-19.webp',
    ],
  },
  {
    id: 17,
    name: 'Modern Dining Table',
    price: 1299,
    discount: 1499,
    category: 'Dining Room',
    style: 'Modern',
    material: 'Wood',
    color: 'Black',
    rating: 4.7,
    reviews: 92,
    stock: 7,
    description:
      'A modern dining table with a sleek design and a solid wood frame. Features a tempered glass top and a metal base.',
    features: [
      'Tempered glass top',
      'Metal base',
      'Easy assembly with included tools',
      'Weight capacity: 1000 lbs',
    ],
    specifications: {
      dimensions: '120" W x 60" D x 30" H',
      weight: '150 lbs',
      material: 'Wood, Glass, Metal',
      assembly: 'Required, tools included',
      warranty: '2 years limited warranty',
    },
    colors: ['Black', 'White', 'Oak'],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    image: '/products/converted-image-16.webp',
    images: [
      '/products/converted-image-17.webp',
      '/products/converted-image-18.webp',
      '/products/converted-image-19.webp',
      '/products/converted-image-20.webp',
    ],
  },
]

// Wishlist data
export const wishlist = [
  {
    id: 1,
    name: 'Leather Recliner',
    price: 799,
    image: '/placeholder.svg?height=200&width=200',
  },
  {
    id: 2,
    name: 'Bookshelf',
    price: 349,
    image: '/placeholder.svg?height=200&width=200',
  },
  {
    id: 3,
    name: 'Desk Lamp',
    price: 129,
    image: '/placeholder.svg?height=200&width=200',
  },
]

// Address data
export const addresses = [
  {
    id: 1,
    type: 'Home',
    default: true,
    name: 'Sarah Johnson',
    street: '123 Main Street',
    city: 'San Francisco',
    state: 'CA',
    zip: '94105',
    country: 'United States',
    phone: '+1 (555) 123-4567',
  },
  {
    id: 2,
    type: 'Work',
    default: false,
    name: 'Sarah Johnson',
    street: '456 Market Street',
    city: 'San Francisco',
    state: 'CA',
    zip: '94103',
    country: 'United States',
    phone: '+1 (555) 987-6543',
  },
]

// Helper functions to get data
export function getProductById(id: number | string) {
  const numericId = typeof id === 'string' ? Number.parseInt(id) : id
  return products.find(product => product.id === numericId)
}

export function getProductsByCategory(category: string) {
  if (!category) return products
  return products.filter(
    product =>
      product.category.toLowerCase().replace(/\s+/g, '-') ===
      category.toLowerCase(),
  )
}

export function getFeaturedProducts() {
  return products.filter(product => product.isFeatured)
}

export function getNewArrivals() {
  return products.filter(product => product.isNew)
}

export function getBestsellers() {
  return products.filter(product => product.isBestseller)
}

export function getRelatedProducts(productId: number, limit = 4) {
  const product = getProductById(productId)
  if (!product) return []

  return products
    .filter(p => p.id !== productId && p.category === product.category)
    .slice(0, limit)
}
